name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm --prefix ./source/ ci

      - name: Lint source
        run: npm --prefix ./source/ run lint-check
