name: Super-Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Super-Linter
        uses: github/super-linter@v3
        with:
          valid_file_extensions: ""
          debug: false
          default_branch: main
          allowlist: ""

      - name: Run Super-Linter
        run: ./entrypoint.sh
